#!/bin/sh
# Zero phase 15 -- the character classes, the numbers and the sort.  See ZERO-GOAL.md.
#
# Usage: pipes/zero15-edit.sh <work-dir> <state-dir>     (run from the repository root)
#
# THE CHARTER SAYS "no musl dependencies in `zero-vim.c` itself".  Phase 14 took the
# strings; this takes everything else that is PURE COMPUTATION -- a function of its
# arguments that asks the operating system nothing -- and defines it in the file, as
# plain C, with no preprocessor and no comment.  Eleven undefined symbols go:
#
#   character classes  tolower toupper towlower towupper isalnum iscntrl ispunct
#   numbers            atoi atol
#   sorting            qsort bsearch
#
# AND `nm -u` IS NOT THE SCOPE, which is the whole reason this phase is bigger than
# that list.  musl spells six more classifiers as FUNCTION-LIKE MACROS in
# <ctype.h> -- `isalpha isdigit isgraph islower isupper`, and `isspace` through
# `__isspace` -- so a source that calls them produces no undefined symbol at all.
# Five of them are live here, at 17 sites, and until they go <ctype.h> cannot.  A
# phase scoped by `nm -u` would look finished and leave phase 16 unable to move.
#
# <wctype.h> HAS A THIRD USER AND IT IS A DEAD STATEMENT.  `iswupper` is named once,
# at the line after `return utf_isupper(c);` inside `vim_isupper` -- the residue of
# whim folding `if (enc_utf8)` to always-true.  gcc drops the unreachable block even
# at -O0, which is why the name is in the source and not in `nm -u`.  It is deleted
# rather than vendored, and that is measured rather than asserted: same file name,
# SOURCE_DATE_EPOCH=0, the binary is BYTE-IDENTICAL either side.
#
# NOTHING IN tools/sweep.sh COVERS AN UNREACHABLE STATEMENT, and that is a gap worth
# naming rather than a thing to fix here.  gcc's -Wunreachable-code has been a no-op
# since gcc 4.5 and is not in -Wall -Wextra; tools/deadsweep.py acts on warnings;
# funcreach.py and typereach.py read DEFINITIONS, and `iswupper` is a libc name with
# no definition in this file.  Measured: `zero-vim.c` holds EIGHTEEN statements that
# cannot run, and exactly ONE of them names a libc symbol.  This phase takes that
# one.  The other seventeen are a phase of their own: three of them are the folded
# Latin-1 arms of these same four functions, and deleting those would orphan
# `latin1flags`, `latin1upper` and `latin1lower` -- which would turn a vendoring
# phase into a cut.
#
# WHY towupper AND towlower ARE THE HARD ONES, and what was measured before choosing.
# Their one live arm each is `if (!(cmp_flags & CMP_INTERNAL)) return towupper(a);`
# inside `utf_toupper`/`utf_tolower`, and `'casemap'` defaults to
# "internal,keepascii" -- so the obvious reading is "unreachable unless the user
# types `:set casemap=`".  THAT READING IS WRONG.  An instrumented build marks 104
# of the 106 records of a full recording, 892 times in one trivial session: the
# caller is `utf_islower`/`utf_isupper` from `buf_init_chartab()`, running BEFORE
# 'casemap' has been applied, with `cmp_flags` still its static zero and arguments
# in exactly 128..255.  They classify the whole Latin-1 range at startup.
#
# FOUR ANSWERS WERE BUILT AND RECORDED.  musl implements them with a two-level
# base-6 packed table (src/ctype/casemap.h, 297 lines) and forty lines of bit
# arithmetic: exact, and the opposite of "obvious, simple, idiomatic C".  Routing
# them to vim's own table instead costs 96 upper and 96 lower codepoints above
# U+00FF and is a declared behaviour change.  An ASCII-only fallback misclassifies
# 62 of 128 Latin-1 bytes at startup and EVERY HARNESS HERE SAYS IT IS FINE, because
# 'isprint' ("@,161-255") and 'iskeyword' ("@,48-57,_,192-255") re-cover the same
# bytes by range -- which is why that one is rejected with a number rather than an
# opinion.  What runs is the fourth: musl's mapping RANGE-COMPRESSED INTO THE SHAPE
# THIS FILE ALREADY HAS, 187 + 171 `convertStruct` rows read by `utf_convert()`, the
# same size as vim's own 198 + 183 and read by the same function.  Exact, and in the
# file's own idiom.
#
# THE TWO DATA FILES ARE NOT REMEMBERED CONSTANTS, and the check is what makes that
# true.  tools/musl-case.txt is generated by `muslcase --generate`, which
# reads THIS MACHINE'S libc through ctypes; `--verify` re-derives every one of the
# 1,114,112 codepoints from the same authority and refuses on one disagreement.
# tools/musl-ctype.txt is the seventeen functions, and muslctype compiles
# them OUT OF THE SOURCE THIS PHASE PRODUCES and runs them beside libc's.  Neither
# check trusts the bytes it shipped.
#
# THREE ANCHORS AND SIXTEEN COUNTED REWRITES.
#
#   A  the seventeen functions and two prototypes, at the END OF THE BLOCK PHASE 14
#      STARTED -- between the last #include and the enum wall -- so the file has one
#      vendored block and not two.  The anchor is the junction itself, the end of
#      `musl_fmtptr` and the first enum.  The prototypes are needed only because the
#      two DEAD `return towupper(c);` mentions are rewritten too and sit below.
#
#      THE SEVENTEEN USE THE FILE'S TWO-LINE DEFINITION STYLE, and that is mechanical
#      rather than cosmetic.  tools/funcreach.py finds a definition with
#      `^([A-Za-z_]\w*)\(...\)$` -- the NAME at column 0, which is what
#      `    static int` on its own line gives.  Phase 14 wrote one-line headers
#      (`static void *musl_memcpy(...)`), and MEASURED, funcreach.py sees 1,719
#      definitions on this phase's input, exactly as it did before phase 14 ran: not
#      one of its nineteen is in the reachability graph.  Nothing is wrong today --
#      the block calls nothing funcreach tracks, and gcc's -Wunused-function still
#      covers a dead one -- but a function written that way is outside the sweep, so
#      these seventeen are written the way the other 1,719 are.
#   B  the two tables and their wrappers, after vim's own `toUpper[]` -- so musl's
#      sit beside vim's and `utf_convert()` is already declared above them.
#   C  `return iswupper(c);`, deleted.
#   D  sixteen call-site rewrites, each counted file-wide, applied ONLY to the text
#      after the inserted block so that the block's own bodies are never rewritten.
#
# THE DECLARED DELTA IS NOTHING AT ALL, and it is the third kind of empty
# declaration this pipeline has.  Phase 9's was code that could not run; phase 13's
# was a possibility that had never existed; THIS ONE IS AN EQUALITY -- the code runs
# constantly and computes the same answer, so the evidence is equivalence rather
# than unreachability, and every probe is a MUST-NOT-DIFFER.
set -eu

work=${1:?usage: zero15-edit.sh <work-dir> <state-dir>}
state=${2:?usage: zero15-edit.sh <work-dir> <state-dir>}
f="$work/zero-vim.c"

# The flags are read out of the boundary's makefile rather than written here a
# second time: zero's compile line is the boundary's (ZERO-GOAL.md rule 8).  The
# check needs the binary this phase was HANDED, to run its probes on both sides.
cflags=$(sed -n 's/^CFLAGS  *= *//p' "$work/Makefile")
ldflags=$(sed -n 's/^LDFLAGS  *= *//p' "$work/Makefile")
cp "$f" "$state/old.c"
# shellcheck disable=SC2086
( cd "$state" && gcc $cflags $ldflags -o old old.c ) &
pid_old=$!

tools/st.sh edit zero15 "$f" tools/musl-ctype.txt tools/musl-case.txt

# An edit that starts a background job waits for it before it exits (tools/phaserun.sh).
wait $pid_old || { echo "  vendor       the input binary did not build with '$cflags' '$ldflags'"; exit 1; }
echo "  vendor       the input is $state/old, $(stat -c%s "$state/old") bytes, beside the source it was built from: the delta is nothing at all, so every probe in the check is a MUST-NOT-DIFFER and both binaries run all of them"

# tools/phaserun.sh sweeps next, then runs pipes/zero15-check.sh.
