#!/bin/sh
# Zero phase 15 -- the character classes, the numbers and the sort.  See ZERO-GOAL.md.
#
# Usage: pipes/zero15-edit.sh <work-dir> <state-dir>     (run from the repository root)
#
# THE CHARTER SAYS "no musl dependencies in `zero-vim.c` itself".  Phase 14 took the
# strings; this takes everything else that is PURE COMPUTATION -- a function of its
# arguments that asks the operating system nothing -- and defines it in the file, as
# plain C, with no preprocessor and no comment.  Eleven undefined symbols go:
#
#   character classes  tolower toupper towlower towupper isalnum iscntrl ispunct
#   numbers            atoi atol
#   sorting            qsort bsearch
#
# AND `nm -u` IS NOT THE SCOPE, which is the whole reason this phase is bigger than
# that list.  musl spells six more classifiers as FUNCTION-LIKE MACROS in
# <ctype.h> -- `isalpha isdigit isgraph islower isupper`, and `isspace` through
# `__isspace` -- so a source that calls them produces no undefined symbol at all.
# Five of them are live here, at 17 sites, and until they go <ctype.h> cannot.  A
# phase scoped by `nm -u` would look finished and leave phase 16 unable to move.
#
# <wctype.h> HAS A THIRD USER AND IT IS A DEAD STATEMENT.  `iswupper` is named once,
# at the line after `return utf_isupper(c);` inside `vim_isupper` -- the residue of
# whim folding `if (enc_utf8)` to always-true.  gcc drops the unreachable block even
# at -O0, which is why the name is in the source and not in `nm -u`.  It is deleted
# rather than vendored, and that is measured rather than asserted: same file name,
# SOURCE_DATE_EPOCH=0, the binary is BYTE-IDENTICAL either side.
#
# NOTHING IN tools/sweep.sh COVERS AN UNREACHABLE STATEMENT, and that is a gap worth
# naming rather than a thing to fix here.  gcc's -Wunreachable-code has been a no-op
# since gcc 4.5 and is not in -Wall -Wextra; tools/deadsweep.py acts on warnings;
# funcreach.py and typereach.py read DEFINITIONS, and `iswupper` is a libc name with
# no definition in this file.  Measured: `zero-vim.c` holds EIGHTEEN statements that
# cannot run, and exactly ONE of them names a libc symbol.  This phase takes that
# one.  The other seventeen are a phase of their own: three of them are the folded
# Latin-1 arms of these same four functions, and deleting those would orphan
# `latin1flags`, `latin1upper` and `latin1lower` -- which would turn a vendoring
# phase into a cut.
#
# WHY towupper AND towlower ARE THE HARD ONES, and what was measured before choosing.
# Their one live arm each is `if (!(cmp_flags & CMP_INTERNAL)) return towupper(a);`
# inside `utf_toupper`/`utf_tolower`, and `'casemap'` defaults to
# "internal,keepascii" -- so the obvious reading is "unreachable unless the user
# types `:set casemap=`".  THAT READING IS WRONG.  An instrumented build marks 104
# of the 106 records of a full recording, 892 times in one trivial session: the
# caller is `utf_islower`/`utf_isupper` from `buf_init_chartab()`, running BEFORE
# 'casemap' has been applied, with `cmp_flags` still its static zero and arguments
# in exactly 128..255.  They classify the whole Latin-1 range at startup.
#
# FOUR ANSWERS WERE BUILT AND RECORDED.  musl implements them with a two-level
# base-6 packed table (src/ctype/casemap.h, 297 lines) and forty lines of bit
# arithmetic: exact, and the opposite of "obvious, simple, idiomatic C".  Routing
# them to vim's own table instead costs 96 upper and 96 lower codepoints above
# U+00FF and is a declared behaviour change.  An ASCII-only fallback misclassifies
# 62 of 128 Latin-1 bytes at startup and EVERY HARNESS HERE SAYS IT IS FINE, because
# 'isprint' ("@,161-255") and 'iskeyword' ("@,48-57,_,192-255") re-cover the same
# bytes by range -- which is why that one is rejected with a number rather than an
# opinion.  What runs is the fourth: musl's mapping RANGE-COMPRESSED INTO THE SHAPE
# THIS FILE ALREADY HAS, 187 + 171 `convertStruct` rows read by `utf_convert()`, the
# same size as vim's own 198 + 183 and read by the same function.  Exact, and in the
# file's own idiom.
#
# THE TWO DATA FILES ARE NOT REMEMBERED CONSTANTS, and the check is what makes that
# true.  tools/musl-case.txt is generated by `muslcase --generate`, which
# reads THIS MACHINE'S libc through ctypes; `--verify` re-derives every one of the
# 1,114,112 codepoints from the same authority and refuses on one disagreement.
# tools/musl-ctype.txt is the seventeen functions, and muslctype compiles
# them OUT OF THE SOURCE THIS PHASE PRODUCES and runs them beside libc's.  Neither
# check trusts the bytes it shipped.
#
# THREE ANCHORS AND SIXTEEN COUNTED REWRITES.
#
#   A  the seventeen functions and two prototypes, at the END OF THE BLOCK PHASE 14
#      STARTED -- between the last #include and the enum wall -- so the file has one
#      vendored block and not two.  The anchor is the junction itself, the end of
#      `musl_fmtptr` and the first enum.  The prototypes are needed only because the
#      two DEAD `return towupper(c);` mentions are rewritten too and sit below.
#
#      THE SEVENTEEN USE THE FILE'S TWO-LINE DEFINITION STYLE, and that is mechanical
#      rather than cosmetic.  tools/funcreach.py finds a definition with
#      `^([A-Za-z_]\w*)\(...\)$` -- the NAME at column 0, which is what
#      `    static int` on its own line gives.  Phase 14 wrote one-line headers
#      (`static void *musl_memcpy(...)`), and MEASURED, funcreach.py sees 1,719
#      definitions on this phase's input, exactly as it did before phase 14 ran: not
#      one of its nineteen is in the reachability graph.  Nothing is wrong today --
#      the block calls nothing funcreach tracks, and gcc's -Wunused-function still
#      covers a dead one -- but a function written that way is outside the sweep, so
#      these seventeen are written the way the other 1,719 are.
#   B  the two tables and their wrappers, after vim's own `toUpper[]` -- so musl's
#      sit beside vim's and `utf_convert()` is already declared above them.
#   C  `return iswupper(c);`, deleted.
#   D  sixteen call-site rewrites, each counted file-wide, applied ONLY to the text
#      after the inserted block so that the block's own bodies are never rewritten.
#
# THE DECLARED DELTA IS NOTHING AT ALL, and it is the third kind of empty
# declaration this pipeline has.  Phase 9's was code that could not run; phase 13's
# was a possibility that had never existed; THIS ONE IS AN EQUALITY -- the code runs
# constantly and computes the same answer, so the evidence is equivalence rather
# than unreachability, and every probe is a MUST-NOT-DIFFER.
set -eu

work=${1:?usage: zero15-edit.sh <work-dir> <state-dir>}
state=${2:?usage: zero15-edit.sh <work-dir> <state-dir>}
f="$work/zero-vim.c"

# The flags are read out of the boundary's makefile rather than written here a
# second time: zero's compile line is the boundary's (ZERO-GOAL.md rule 8).  The
# check needs the binary this phase was HANDED, to run its probes on both sides.
cflags=$(sed -n 's/^CFLAGS  *= *//p' "$work/Makefile")
ldflags=$(sed -n 's/^LDFLAGS  *= *//p' "$work/Makefile")
cp "$f" "$state/old.c"
# shellcheck disable=SC2086
( cd "$state" && gcc $cflags $ldflags -o old old.c ) &
pid_old=$!

python3 - "$f" tools/musl-ctype.txt tools/musl-case.txt <<'PY'
TAG = 'vendor'
import re
import sys
path, ctype_txt, case_txt = sys.argv[1], sys.argv[2], sys.argv[3]
t = open(path, errors='surrogateescape').read()


def die(msg):
    sys.exit('  %-12s %s' % (TAG, msg))


def say(what):
    print('  %-12s %s' % (TAG, what))


def calls(text, name):
    """Occurrences of `name` as a CALL, which is what a header provides.

    Not `\\b%s\\b`: "isprint" is also the name of an option and lives in a string
    literal, and a word count says 1 on a file that calls it nowhere.
    """
    return len(re.findall(r'(?<![\w])%s\s*\(' % name, text))


def text_edit(text, old, new, what, n=1):
    """An exact-text replacement, counted file-wide.  Never 'the first one'."""
    k = text.count(old)
    if k != n:
        die('%s -- the text occurs %d times, expected %d: %r'
            % (what, k, n, old[:70]))
    say(what)
    return text.replace(old, new)


# ---- 0. the shape every anchor below was counted against ---------------------------
# The eleven undefined symbols, the six macros that produce none, and the one dead
# statement.  A call count, not a word count, for the reason in calls() above.
BEFORE = {'tolower': 2, 'toupper': 2, 'towlower': 2, 'towupper': 2,
          'isalnum': 2, 'iscntrl': 1, 'ispunct': 1,
          'isalpha': 3, 'isdigit': 7, 'isgraph': 1, 'islower': 1, 'isupper': 5,
          'iswupper': 1,
          'isspace': 0, 'isprint': 0,
          'atoi': 7, 'atol': 3, 'qsort': 1, 'bsearch': 4,
          'utf_convert': 4,           # the function the two tables are read by
          'sort_strings': 3, 'sort_compare': 1}
for name, want in sorted(BEFORE.items()):
    k = calls(t, name)
    if k != want:
        die('%s is called %d times, expected %d -- the anchors below were counted '
            'against a different file' % (name, k, want))
say('eleven undefined symbols at 2 2 2 2 2 1 1 / 7 3 / 1 4 calls, the SIX macros '
    'that produce no undefined symbol at all at 3 7 1 1 5 (isspace 0), and iswupper '
    'at 1 -- the file the three anchors were counted against')

# The two prefixes must be free, because this file is one namespace and a silent
# collision between a tentative definition and a vendored one is exactly what
# CLAUDE.md warns about.
for name in ('musl_isdigit', 'musl_isalpha', 'musl_isupper', 'musl_islower',
             'musl_isgraph', 'musl_isspace', 'musl_isalnum', 'musl_iscntrl',
             'musl_ispunct', 'musl_tolower', 'musl_toupper', 'musl_atoi',
             'musl_atol', 'musl_bsearch', 'musl_qsort', 'musl_towupper',
             'musl_towlower', 'musl_toUpper', 'musl_toLower'):
    if re.search(r'\b%s\b' % name, t):
        die('%s already exists in the file' % name)
say('the nineteen musl_ names this phase defines are all free')

# ---- THE INVARIANT, COMPUTED BEFORE ANYTHING IS INSERTED ----------------------------
# Two of the four `tow*` mentions are DEAD: they sit on the line after an
# unconditional `return`, gcc drops the unreachable block even at -O0, and that is
# why `iswupper` -- whose ONLY mention has that shape -- is in the source and not in
# `nm -u`.  Rewriting them is harmless and leaving them is not an option, because
# phase 16 removes the header they name.  The count is asserted so that a phase that
# had made one of them live would fail here.
dead = re.findall(r'^ *return utf_is(?:upper|lower)\(c\);\n *if \(c >= 0x100\)$',
                  t, re.M)
if len(dead) != 2:
    die('the two dead `if (c >= 0x100)` arms of vim_isupper/vim_islower are not '
        'where this phase found them (%d)' % len(dead))
say('vim_isupper and vim_islower still open with `return utf_is*(c);` followed by an '
    'unreachable `if (c >= 0x100)` -- which is the shape that makes iswupper a name '
    'in the source and not a symbol in the object')

# ---- A. the seventeen functions, after NGETTEXT ---------------------------------------
BLOCK = open(ctype_txt).read()
# THE BLOCK JOINS PHASE 14'S RATHER THAN STARTING A SECOND ONE.  Phase 14 put its
# nineteen string functions at the top of the file, between the last #include and the
# enum wall, so the anchor is that JUNCTION -- the end of its last definition and the
# first enum -- and not a line of its own.  Written this way the edit refuses loudly
# if phase 14's block ever ends somewhere else, which is what a counted anchor is for.
TAIL = ("    dest[18] = '\\0';\n"
        '    return 18;\n'
        '}\n')
WALL = '\nenum { BH_DIRTY = 1 };\n'
t = text_edit(t, TAIL + WALL, TAIL + BLOCK + WALL,
              'the seventeen functions go at the END OF PHASE 14\'s BLOCK, before the '
              'enum wall -- one vendored block and not two -- defined before every '
              'use, so only the two dead tow* mentions need a prototype')

# ---- B. the two tables, beside vim's own -----------------------------------------------
CASE = open(case_txt).read()
TOUPPER_END = '        {0x1e922,0x1e943,1,-34}\n};\n'
t = text_edit(t, TOUPPER_END, TOUPPER_END + CASE,
              "musl's case mapping as 187 + 171 convertStruct rows, after vim's own "
              'toUpper[] -- the same shape, the same size, and read by the '
              'utf_convert() that is already declared above them')

# ---- C. the dead statement ---------------------------------------------------------------
t = text_edit(t, '            return iswupper(c);\n', '',
              "vim_isupper's `return iswupper(c);`, which cannot run and is "
              "<wctype.h>'s last user besides the two this phase vendors -- deleting "
              'it is byte-identical, measured with SOURCE_DATE_EPOCH=0')

# ---- D. the call sites, counted, and only BELOW the block ---------------------------------
# The rewrites are applied to the text after the inserted functions so that the
# block's own bodies -- musl_ispunct calls musl_isalnum, musl_atoi calls
# musl_isdigit -- are never themselves rewritten.  A file-wide regex would have
# turned musl_tolower's body into musl_musl_tolower.
cut = t.index(BLOCK) + len(BLOCK)
head, body = t[:cut], t[cut:]
REWRITE = [('tolower', 2), ('toupper', 2), ('towlower', 2), ('towupper', 2),
           ('isalnum', 2), ('iscntrl', 1), ('ispunct', 1),
           ('isalpha', 3), ('isdigit', 7), ('isgraph', 1), ('islower', 1),
           ('isupper', 5),
           ('atoi', 7), ('atol', 3), ('qsort', 1), ('bsearch', 4)]
for name, want in REWRITE:
    pat = r'(?<![\w])%s\s*\(' % name
    k = len(re.findall(pat, body))
    if k != want:
        die('%s is called %d times below the inserted block, expected %d'
            % (name, k, want))
    body = re.sub(pat, 'musl_%s(' % name, body)
t = head + body
say('sixteen counted rewrites: tolower 2, toupper 2, towlower 2, towupper 2, '
    'isalnum 2, iscntrl 1, ispunct 1, isalpha 3, isdigit 7, isgraph 1, islower 1, '
    'isupper 5, atoi 7, atol 3, qsort 1, bsearch 4 -- 44 call sites, every one of '
    'them BELOW the block, so no vendored body rewrites itself')

# ---- what the sweep is handed, as a count rather than as trust -------------------------
# Every name <ctype.h> and <wctype.h> could still be providing must be called
# nowhere.  This is the contract phase 16 removes the two headers on, and it is
# stated here so that a miss fails THIS phase instead of that one.
PROVIDED = ('isalnum isalpha isblank iscntrl isdigit isgraph islower isprint '
            'ispunct isspace isupper isxdigit isascii toascii tolower toupper '
            'iswalnum iswalpha iswblank iswcntrl iswdigit iswgraph iswlower '
            'iswprint iswpunct iswspace iswupper iswxdigit towlower towupper '
            'towctrans wctrans wctype iswctype').split()
left = [n for n in PROVIDED if calls(t, n)]
if left:
    die('<ctype.h>/<wctype.h> still has a user and phase 16 could not remove it: %s'
        % ' '.join(left))
for tname in ('wint_t', 'wctype_t', 'wctrans_t'):
    if re.search(r'\b%s\b' % tname, t):
        die('%s is still named, and it is <wctype.h>\'s' % tname)
say('nothing <ctype.h> or <wctype.h> provides is called anywhere, and no wint_t, '
    'wctype_t or wctrans_t is named -- which is the contract phase 16 removes the '
    'two headers on, asserted here so that a miss fails THIS phase')
if calls(t, 'iswupper') or re.search(r'\biswupper\b', t):
    die('iswupper survives')
directives = [l for l in t.splitlines() if l.startswith('#')]
if len(directives) != 18 or any(not l.startswith('#include <') for l in directives):
    die('the directives are no longer 18 #includes of a system header: %d, %s'
        % (len(directives), ' '.join(l for l in directives if not l.startswith('#include <'))))
say('18 directives, every one an #include of a system header -- this phase adds no '
    'preprocessor and removes none; the two it makes unnecessary are phase 16\'s')

open(path, 'w', errors='surrogateescape').write(t)
PY

# An edit that starts a background job waits for it before it exits (tools/phaserun.sh).
wait $pid_old || { echo "  vendor       the input binary did not build with '$cflags' '$ldflags'"; exit 1; }
echo "  vendor       the input is $state/old, $(stat -c%s "$state/old") bytes, beside the source it was built from: the delta is nothing at all, so every probe in the check is a MUST-NOT-DIFFER and both binaries run all of them"

# tools/phaserun.sh sweeps next, then runs pipes/zero15-check.sh.
