#!/bin/sh
# The per-tool breakdown: every single-file cutter against every corpus input,
# Go beside Python, counted per tool and written as a table.
#
# Usage: sh tools/gocmp/cuttable.sh [outfile]      (run from the repository root)
#
# WHY THIS EXISTS AND pcutcmp.sh DOES NOT SUFFICE.  pcutcmp already runs every
# comparison and already writes one verdict per (tool, input) pair -- and then
# deletes the directory holding them and prints ONE aggregate line.  What was
# committed as the Go port's evidence was that line: "57 cutters, 32,595
# comparisons, 0 differences, 2,230 real cuts".  A single aggregate with no
# breakdown behind it is the shape of claim that has now failed this work
# twice: once as "the wrappers name their Go sources so implhash hashes them",
# which was false, and once as "the cutters are verified", which was true in
# bulk and unrecorded per tool.  A number nobody can attribute is a number
# nobody can falsify.
#
# THE TOOL LIST IS DERIVED, NEVER TYPED.  It is the intersection of what whim
# and zero phases actually name with what the binary actually implements,
# restricted to the subcommands whose usage is exactly `<name> <file>`.  A
# hand-kept list is the artifact that failed in tools/sweep.sh -- eighteen of a
# hundred and twenty-eight files, four of them ones the sweep reaches -- and
# there is no reason to make a second one here.
#
# A TOOL THAT CUT NOTHING IS REPORTED AND FAILS THE RUN.  Agreement on a
# refusal is agreement about an anchor, not about a cut, and a tool whose
# anchors refuse on every input in the corpus has been compared on nothing.
# That is pcutcmp's own rule, applied per tool instead of once over all of
# them -- which is the difference this script is for, because the aggregate
# passed while any individual tool could have been vacuous inside it.
set -eu

[ -d tools ] && [ -d pipes ] || { echo "cuttable: run me from the repository root" >&2; exit 1; }
out=${1:-tools/gocmp/CUTTERS.md}
corpus=${GOCMP_CORPUS:-.gocorpus}
BIN=$PWD/$(sh tools/gobuild.sh)
export BIN

inputs=$(ls "$corpus"/*/*.c 2>/dev/null | wc -l)
[ "$inputs" -gt 0 ] || { echo "cuttable: $corpus holds no .c - build it with tools/gocorpus.sh" >&2; exit 1; }

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

"$BIN" 2>&1 | sed -n 's/^    \([a-z0-9]*\) .*/\1/p' | sort -u > "$work/all"
"$BIN" 2>&1 | sed -n 's/^    \([a-z0-9]*\) <file>$/\1/p' | sort -u > "$work/onefile"
grep -ohE 'tools/[a-z0-9_]+\.py' pipes/whim*.sh pipes/zero*.sh |
    sed 's|tools/||; s|\.py||' | sort -u > "$work/used"
comm -12 "$work/used" "$work/all" | comm -12 - "$work/onefile" > "$work/tools"

ntools=$(wc -l < "$work/tools")
echo "cuttable: $ntools tools x $inputs inputs = $((ntools * inputs)) comparisons" >&2

OUT="$work/v"; mkdir -p "$OUT"; export OUT
for tool in $(cat "$work/tools"); do
    for src in "$corpus"/*/*.c; do
        printf '%s\n%s\n' "$tool" "$src"
    done
done | xargs -P "$(nproc)" -n 2 sh "${GOCMP:-tools/gocmp}"/pcutone.sh

{
    echo "# The Go cutters against their Python, per tool"
    echo
    echo "Generated by \`tools/gocmp/cuttable.sh\`. Every tool whim or zero names"
    echo "that has a single-file Go subcommand, run over every input in the corpus,"
    echo "Go beside Python, with the two outputs and the two messages compared."
    echo
    echo "\`cut\` is a comparison where the Python CHANGED the file; \`refused\` is one"
    echo "where its anchors declined. Only the first is evidence about a cut, which"
    echo "is why it is counted separately and why a tool with none fails this run."
    echo
    echo "| tool | inputs | same | differ | cut | refused | py-raised |"
    echo "| --- | ---: | ---: | ---: | ---: | ---: | ---: |"
} > "$out"

fail=0
vacuous=
tsame=0; tdiff=0; tcut=0; tref=0; tcrash=0
for tool in $(cat "$work/tools"); do
    s=0; d=0; c=0; r=0; x=0
    for f in "$OUT/$tool".*; do
        [ -f "$f" ] || continue
        case "$(head -1 "$f")" in
            "same cut")     s=$((s+1)); c=$((c+1)) ;;
            "same refused") s=$((s+1)); r=$((r+1)) ;;
            "same crash")   s=$((s+1)); x=$((x+1)) ;;
            differ*)        d=$((d+1)) ;;
        esac
    done
    n=$((s + d))
    printf '| `%s` | %d | %d | %d | %d | %d | %d |\n' "$tool" "$n" "$s" "$d" "$c" "$r" "$x" >> "$out"
    tsame=$((tsame+s)); tdiff=$((tdiff+d)); tcut=$((tcut+c)); tref=$((tref+r)); tcrash=$((tcrash+x))
    if [ "$d" -ne 0 ]; then
        echo "DIFFER $tool: $d of $n" >&2
        grep -h -A3 '^differ' "$OUT/$tool".* 2>/dev/null | head -12 >&2
        fail=1
    fi
    if [ "$c" -eq 0 ]; then
        echo "VACUOUS $tool: $n comparisons and not one of them cut anything" >&2
        vacuous="$vacuous $tool"
        fail=1
    fi
done

{
    printf '| **total** | **%d** | **%d** | **%d** | **%d** | **%d** | **%d** |\n' \
        "$((tsame + tdiff))" "$tsame" "$tdiff" "$tcut" "$tref" "$tcrash"
    echo
    echo "Corpus: \`$corpus\`, $inputs inputs."
    echo
    echo "## The tools this corpus cannot judge"
    echo
    echo "A row with \`cut\` = 0 was compared on nothing: every input made its anchors"
    echo "refuse, so the agreement is about a refusal and not about a cut. That is"
    echo "derivable from the table above and is listed here so it cannot be skimmed"
    echo "past. These need a per-tool corpus from \`tools/gocmp/toolinput.sh\`, which"
    echo "truncates the owning phase's edit at the tool's own invocation."
    echo
    for v in $vacuous; do echo "- \`$v\`"; done
    echo
    echo "**$(echo $vacuous | wc -w) of $ntools.** The aggregate these replace -- one line saying 0"
    echo "differences over the whole set -- was true and concealed every one of them,"
    echo "which is the whole reason this table is per tool."
    echo
    echo "\`py-raised\` counts the inputs where the PYTHON raises rather than refusing"
    echo "cleanly -- \`cutil.drop_if\` throws \`ValueError\` and no caller catches it --"
    echo "where the Go refuses with one line. Those two cannot agree textually, so what"
    echo "is required of them is the property that matters: both exit non-zero and"
    echo "neither writes the file."
} >> "$out"

echo "cuttable: wrote $out -- $tsame same, $tdiff differ, $tcut cut, $tref refused, $tcrash py-raised" >&2
[ "$fail" -eq 0 ]
