package edit

// The multi-line literals /root/.claude/jobs/107d6bd5/tmp/w74.sh matches on, EXTRACTED from the phase's
// heredoc by tools/gocmp/genlits.py rather than retyped.  They carry BLANK
// LINES, which a filtered read of a phase program does not show, and a
// literal that is 90%% right matches nothing.  See that tool for the
// measurement.
const (
	w74lit1 = "Delete a brace-matched block, anchored on the line that opens it, n times.\n\n    Brace matching rather than a line pattern, because these bodies are\n    macro-expanded one-liners hundreds of characters wide -- transcribing them is\n    exactly what killed this phase's first attempt.\n    "
	w74lit2 = "    int         i;\n\n    for (i = 0; i <  ('z' - 'a' + 1) ; i++)\n    {\n        buf->b_namedm[i].lnum = 0;\n    }\n    buf->b_op_start.lnum = 0;\n    buf->b_op_end.lnum = 0;\n    buf->b_last_cursor.lnum = 1;\n    buf->b_last_cursor.col = 0;\n    buf->b_last_cursor.coladd = 0;\n    buf->b_last_insert.lnum = 0;\n    buf->b_last_change.lnum = 0;\n    buf->b_changelistlen = 0;\n"
	w74lit3 = "    char_u      *p;\n    int from;\n    int to;\n    int         i;\n\n    if (*eap->arg == NUL && eap->forceit)\n    {\n        clrallmarks(curbuf);\n    }\n    else if (eap->forceit)\n    {\n        emsg(_(e_invalid_argument));\n    }\n    else if (*eap->arg == NUL)\n    {\n        emsg(_(e_argument_required));\n    }\n    else\n    {\n        for (p = eap->arg; *p != NUL; ++p)\n        {\n            if ( ((unsigned)(*p) - 'a' < 26) )\n            {\n                if (p[1] == '-')\n                {\n                    from = *p;\n                    to = p[2];\n                    if (! ((unsigned)(p[2]) - 'a' < 26)  || to < from)\n                    {\n                        semsg(_(e_invalid_argument_str), p);\n                        return;\n                    }\n                    p += 2;\n                }\n                else\n                {\n                    from = to = *p;\n                }\n\n                for (i = from; i <= to; ++i)\n                {\n                    curbuf->b_namedm[i - 'a'].lnum = 0;\n                }\n            }\n            else\n            {\n                switch (*p)\n                {\n                    case '\"':\n                        curbuf->b_last_cursor.lnum = 0;\n                        break;\n                    case '^':\n                        curbuf->b_last_insert.lnum = 0;\n                        break;\n                    case '.':\n                        curbuf->b_last_change.lnum = 0;\n                        break;\n                    case '[':\n                        curbuf->b_op_start.lnum    = 0;\n                        break;\n                    case ']':\n                        curbuf->b_op_end.lnum      = 0;\n                        break;\n                    case '<':\n                        curbuf->b_visual.vi_start.lnum = 0;\n                        break;\n                    case '>':\n                        curbuf->b_visual.vi_end.lnum   = 0;\n                        break;\n                    case ' ':\n                        break;\n                    default:\n                        semsg(_(e_invalid_argument_str), p);\n                              return;\n                }\n            }\n        }\n    }\n"
	w74lit4 = "typedef struct xfilemark\n{\n    fmark_T     fmark;\n    char_u      *fname;\n} xfmark_T;\n\n"
	w74lit5 = "}\n"
	w74lit6 = "\n"
	w74lit7 = "{\n"
)
