package edit

// The multi-line literals /root/.claude/jobs/107d6bd5/tmp/w71.sh matches on, EXTRACTED from the phase's
// heredoc by tools/gocmp/genlits.py rather than retyped.  They carry BLANK
// LINES, which a filtered read of a phase program does not show, and a
// literal that is 90%% right matches nothing.  See that tool for the
// measurement.
const (
	w71AddrPair1     = "                    case ADDR_LOADED_BUFFERS:\n                        {\n                            buf_T       *buf = firstbuf;\n\n                            while (buf->b_next != NULL && buf->b_ml.ml_mfp == NULL)\n                            {\n                                buf = buf->b_next;\n                            }\n                            eap->line1 = buf->b_fnum;\n                            buf = lastbuf;\n                            while (buf->b_prev != NULL && buf->b_ml.ml_mfp == NULL)\n                            {\n                                buf = buf->b_prev;\n                            }\n                            eap->line2 = buf->b_fnum;\n                            break;\n                        }\n                    case ADDR_BUFFERS:\n                        eap->line1 = firstbuf->b_fnum;\n                        eap->line2 = lastbuf->b_fnum;\n                        break;\n"
	w71NewPair1      = "                    case ADDR_LOADED_BUFFERS:\n                    case ADDR_BUFFERS:\n                        eap->line1 = curbuf->b_fnum;\n                        eap->line2 = curbuf->b_fnum;\n                        break;\n"
	w71AddrPair2     = "        case ADDR_LOADED_BUFFERS:\n            {\n                buf_T *buf = firstbuf;\n\n                while (buf->b_next != NULL && buf->b_ml.ml_mfp == NULL)\n                {\n                    buf = buf->b_next;\n                }\n                eap->line1 = buf->b_fnum;\n                buf = lastbuf;\n                while (buf->b_prev != NULL && buf->b_ml.ml_mfp == NULL)\n                {\n                    buf = buf->b_prev;\n                }\n                eap->line2 = buf->b_fnum;\n            }\n            break;\n        case ADDR_BUFFERS:\n            eap->line1 = firstbuf->b_fnum;\n            eap->line2 = lastbuf->b_fnum;\n            break;\n"
	w71NewPair2      = "        case ADDR_LOADED_BUFFERS:\n        case ADDR_BUFFERS:\n            eap->line1 = curbuf->b_fnum;\n            eap->line2 = curbuf->b_fnum;\n            break;\n"
	w71AddrPair3     = "                    case ADDR_LOADED_BUFFERS:\n                        buf = lastbuf;\n                        while (buf->b_ml.ml_mfp == NULL)\n                        {\n                            if (buf->b_prev == NULL)\n                            {\n                                break;\n                            }\n                            buf = buf->b_prev;\n                        }\n                        lnum = buf->b_fnum;\n                        break;\n                    case ADDR_BUFFERS:\n                        lnum = lastbuf->b_fnum;\n                        break;\n"
	w71NewPair3      = "                    case ADDR_LOADED_BUFFERS:\n                    case ADDR_BUFFERS:\n                        lnum = curbuf->b_fnum;\n                        break;\n"
	w71AddrPair4     = "            case ADDR_LOADED_BUFFERS:\n                buf = firstbuf;\n                while (buf->b_ml.ml_mfp == NULL)\n                {\n                    if (buf->b_next == NULL)\n                    {\n                        return _(e_invalid_range);\n                    }\n                    buf = buf->b_next;\n                }\n                if (eap->line1 < buf->b_fnum)\n                {\n                    return _(e_invalid_range);\n                }\n                buf = lastbuf;\n                while (buf->b_ml.ml_mfp == NULL)\n                {\n                    if (buf->b_prev == NULL)\n                    {\n                        return _(e_invalid_range);\n                    }\n                    buf = buf->b_prev;\n                }\n                if (eap->line2 > buf->b_fnum)\n                {\n                    return _(e_invalid_range);\n                }\n                break;\n"
	w71NewPair4      = "            case ADDR_LOADED_BUFFERS:\n                if (curbuf->b_ml.ml_mfp == NULL || eap->line1 < curbuf->b_fnum || eap->line2 > curbuf->b_fnum)\n                {\n                    return _(e_invalid_range);\n                }\n                break;\n"
	w71OldReuseStart = "        if ((flags & BLN_REUSE) && buf_reuse.ga_len > 0)\n        {\n            --buf_reuse.ga_len;\n            buf->b_fnum = ((int *)buf_reuse.ga_data)[buf_reuse.ga_len];\n"
	w71OldReuseEnd   = "        else\n        {\n            buf->b_fnum = top_file_num++;\n        }\n"
	w71lit1          = "Turn `for ((v) = firstbuf; ...)` + block into `v = curbuf;` + the block body.\n\n    REFUSES a body with a `break` or `continue` at the loop's own level.  Deleting\n    the `for` header rebinds such a statement to whatever encloses it, or to nothing\n    at all -- getout()'s walk did exactly that here and produced \"break statement not\n    within loop or switch\".  It is the same hazard CLAUDE.md records for unwrapping\n    do { } while (0), and it must be a refusal rather than a silent miscompile.\n    "
	w71lit2          = "Replace `for (<head>)` and the block it runs with `repl`.\n\n    The head is matched as a REGEX, never as a literal, and that is deliberate:\n    these walk lines are macro-expanded and carry a trailing space after the\n    closing paren.  A literal written out in a shell heredoc is a bad place to\n    depend on invisible whitespace, and one written that way already failed here.\n    "
	w71lit3          = "    return buf == curbuf;\n"
	w71lit4          = "    return bufIsChanged(curbuf);\n"
	w71lit5          = "    if ((curbuf->b_flags & BF_DUMMY) == 0 && !otherfile_buf(curbuf, ffname, stp))\n    {\n        return curbuf;\n    }\n    return NULL;\n"
	w71lit6          = "        if (curbuf->b_ml.ml_mfp != NULL)\n        {\n            bufref_T bufref;\n\n            set_bufref(&bufref, curbuf);\n            apply_autocmds(EVENT_BUFUNLOAD, curbuf->b_fname, curbuf->b_fname, FALSE, curbuf);\n        }\n"
	w71lit7          = "    int         match = -1;\n    char_u      *pat;\n    char_u      *patend;\n    int         attempt;\n    char_u      *p;\n    int         toggledollar;\n\n    if ((pattern_end == pattern + 1 && (*pattern == '%' || *pattern == '#')) || (in_vim9script() && pattern_end == pattern + 2 && pattern[0] == '%' && pattern[1] == '%'))\n    {\n        if (*pattern == '#' || pattern_end == pattern + 2)\n        {\n            match = 0;\n        }\n        else\n        {\n            match = curbuf->b_fnum;\n        }\n    }\n\n    else\n    {\n        pat = file_pat_to_reg_pat(pattern, pattern_end, NULL, FALSE);\n        if (pat == NULL)\n        {\n            return -1;\n        }\n        patend = pat +  strlen((char *)(pat))  - 1;\n        toggledollar = (patend > pat && *patend == '$');\n\n        for (attempt = 0; attempt <= 3; ++attempt)\n        {\n            regmatch_T      regmatch;\n\n            if (toggledollar)\n            {\n                *patend = (attempt < 2) ? NUL : '$';\n            }\n            p = pat;\n            if (*p == '^' && !(attempt & 1))\n            {\n                ++p;\n            }\n            regmatch.regprog = vim_regcomp(p, magic_isset() ? RE_MAGIC : 0);\n            if (regmatch.regprog == NULL)\n            {\n                vim_free(pat);\n                return -1;\n            }\n            if (buflist_match(&regmatch, curbuf, FALSE) != NULL)\n            {\n                match = curbuf->b_fnum;\n            }\n            vim_regfree(regmatch.regprog);\n            if (match >= 0)\n            {\n                break;\n            }\n        }\n\n        vim_free(pat);\n    }\n\n    if (match < 0)\n    {\n        semsg(_(e_no_matching_buffer_for_str), pattern);\n    }\n    return match;\n"
	w71lit8          = "    bufcount = 1;\n"
	w71lit9          = "    return curbuf->b_fnum;\n"
	w71lit10         = "for (bp = firstbuf; ; bp = bp->b_next)\n"
	w71lit11         = "for (bp = curbuf; ; bp = NULL)\n"
	w71lit12         = "    buf_T       *b_next;\n    buf_T       *b_prev;\n\n"
	w71lit13         = "        buf->b_fnum = top_file_num++;\n"
	w71lit14         = "}\n"
	w71lit15         = "\n        emsg(_(e_cannot_allocate_buffer_using_other_one));\n        enter_buffer(curbuf);\n        return FAIL;\n"
	w71lit16         = "    if (autocmd_busy)\n    {\n        buf->b_next = au_pending_free_buf;\n        au_pending_free_buf = buf;\n    }\n    else\n    {\n        vim_free(buf);\n        if (curbuf == buf)\n        {\n            curbuf = NULL;\n        }\n    }\n"
	w71lit17         = "    vim_free(buf);\n    if (curbuf == buf)\n    {\n        curbuf = NULL;\n    }\n"
	w71lit18         = "    valid = buf_valid(buf);\n    if ((valid && buf != curbuf) || curwin->w_buffer == NULL)\n    {\n        if (!valid)\n        {\n            enter_buffer(lastbuf);\n        }\n        else\n        {\n            enter_buffer(buf);\n        }\n    }\n"
	w71lit19         = "    if (curwin->w_buffer == NULL)\n    {\n        enter_buffer(buf);\n    }\n"
	w71lit20         = "        buf->b_next = NULL;\n        if (firstbuf == NULL)\n        {\n            buf->b_prev = NULL;\n            firstbuf = buf;\n        }\n        else\n        {\n            lastbuf->b_next = buf;\n            buf->b_prev = lastbuf;\n        }\n        lastbuf = buf;\n\n"
	w71lit21         = "\n"
	w71lit22         = "{\n"
	w71lit23         = " = curbuf;\n"
)
