package edit

// The multi-line literals pipes/zero10-edit.sh matches on, EXTRACTED from the phase's
// heredoc by tools/gocmp/genlits.py rather than retyped.  They carry BLANK
// LINES, which a filtered read of a phase program does not show, and a
// literal that is 90%% right matches nothing.  See that tool for the
// measurement.
const (
	z10lit3  = "    CMD_file,\n"
	z10lit4  = "    if (!(ea.argt & (EX_CMDWIN | EX_LOCK_OK)) && ea.cmdidx != CMD_file && curbuf_locked())\n"
	z10lit5  = "    if (!(ea.argt & (EX_CMDWIN | EX_LOCK_OK)) && curbuf_locked())\n"
	z10lit6  = "    if (ea.cmdidx == CMD_file && *ea.arg != NUL && curbuf_locked())\n    {\n        goto doend;\n    }\n\n"
	z10lit7  = "static buf_T *buflist_new(char_u *ffname_arg, char_u *sfname_arg, linenr_T lnum, int flags);\n"
	z10lit8  = "static buf_T *buflist_new(linenr_T lnum, int flags);\n"
	z10lit9  = "buflist_new(char_u      *ffname_arg, char_u      *sfname_arg, linenr_T    lnum, int         flags)\n"
	z10lit10 = "buflist_new(linenr_T    lnum, int         flags)\n"
	z10lit11 = "    char_u      *ffname = ffname_arg;\n    char_u      *sfname = sfname_arg;\n    buf_T       *buf;\n    stat_T      st;\n"
	z10lit12 = "    buf_T       *buf;\n"
	z10lit13 = "    fname_expand(curbuf, &ffname, &sfname);\n\n    if (sfname == NULL ||  stat(((char *)sfname), (&st))  < 0)\n    {\n        st.st_dev = ( dev_t )-1;\n    }\n    if (ffname != NULL && !(flags & (BLN_DUMMY | BLN_NEW)) && (buf = buflist_findname_stat(ffname, &st)) != NULL)\n    {\n        vim_free(ffname);\n        if (lnum != 0)\n        {\n            buflist_setfpos(buf, (flags & BLN_NOCURWIN) ? NULL : curwin, lnum, (colnr_T)0, FALSE);\n        }\n\n        if ((flags & BLN_NOOPT) == 0)\n        {\n            buf_copy_options(buf, 0);\n        }\n\n        return buf;\n    }\n\n"
	z10lit14 = "        if (buf == NULL)\n        {\n            vim_free(ffname);\n            return NULL;\n        }\n"
	z10lit15 = "        if (buf == NULL)\n        {\n            return NULL;\n        }\n"
	z10lit16 = "    if (ffname != NULL)\n    {\n        buf->b_ffname = ffname;\n        buf->b_sfname = vim_strsave(sfname);\n    }\n\n"
	z10lit17 = "    if ((ffname != NULL && (buf->b_ffname == NULL || buf->b_sfname == NULL)) || buf->b_wininfo == NULL)\n    {\n        if (buf->b_sfname != buf->b_ffname)\n        {\n             vim_free(buf->b_sfname);\n             (buf->b_sfname) = NULL;\n        }\n        else\n        {\n            buf->b_sfname = NULL;\n        }\n         vim_free(buf->b_ffname);\n         (buf->b_ffname) = NULL;\n        if (buf != curbuf)\n"
	z10lit18 = "    if (buf->b_wininfo == NULL)\n    {\n        if (buf != curbuf)\n"
	z10lit19 = "    buf->b_fname = buf->b_sfname;\n"
	z10lit20 = "    if (st.st_dev == ( dev_t )-1)\n    {\n        buf->b_dev_valid = false;\n    }\n    else\n    {\n        buf->b_dev_valid = true;\n        buf->b_dev = st.st_dev;\n        buf->b_ino = st.st_ino;\n    }\n"
	z10lit21 = "    buf->b_dev_valid = false;\n"
	z10lit22 = "    curbuf = buflist_new(NULL, NULL, 1L, BLN_LISTED);\n"
	z10lit23 = "    curbuf = buflist_new(1L, BLN_LISTED);\n"
	z10lit24 = "        char_u *fname = buf->b_fname != NULL ? buf->b_fname : buf->b_ffname;\n\n        semsg(_(e_attempt_to_delete_buffer_that_is_in_use_str), fname != NULL ? fname : (char_u *)\"[No Name]\");\n"
	z10lit25 = "        semsg(_(e_attempt_to_delete_buffer_that_is_in_use_str), (char_u *)\"[No Name]\");\n"
	z10lit26 = "    char_u      *fname;\n    linenr_T    dummy;\n\n    if (buflist_name_nr(0, &fname, &dummy) == FAIL)\n    {\n        if (errmsg)\n        {\n            emsg(_(e_no_alternate_file));\n        }\n        return NULL;\n    }\n    return fname;\n"
	z10lit27 = "    if (errmsg)\n    {\n        emsg(_(e_no_alternate_file));\n    }\n    return NULL;\n"
	z10lit28 = "    if (name != NULL)\n"
	z10lit29 = "buf_spname(buf_T *buf)\n{\n    if (buf->b_fname == NULL)\n    {\n        return buf_get_fname(buf);\n    }\n    return NULL;\n}\n"
	z10lit30 = "buf_spname(buf_T *buf)\n{\n    return buf_get_fname(buf);\n}\n"
	z10lit31 = "buf_get_fname(buf_T *buf)\n{\n    if (buf->b_fname == NULL)\n    {\n        return (char_u *)_(\"[No Name]\");\n    }\n    return buf->b_fname;\n}\n"
	z10lit32 = "buf_get_fname(buf_T *buf)\n{\n    return (char_u *)_(\"[No Name]\");\n}\n"
	z10lit33 = "        if (semsg(_(e_no_write_since_last_change_for_buffer_str), buf_spname(buf) != NULL ? buf_spname(buf) : buf->b_fname))\n"
	z10lit34 = "        if (semsg(_(e_no_write_since_last_change_for_buffer_str), buf_spname(buf)))\n"
	z10lit35 = "check_fname(void)\n{\n    if (curbuf->b_ffname == NULL)\n    {\n        emsg(_(e_no_file_name));\n        return FAIL;\n    }\n    return OK;\n}\n"
	z10lit36 = "check_fname(void)\n{\n    emsg(_(e_no_file_name));\n    return FAIL;\n}\n"
	z10lit37 = "    return file_name_in_line(ml_get_curline(), curwin->w_cursor.col, options, count, curbuf->b_ffname, file_lnum);\n"
	z10lit38 = "    return file_name_in_line(ml_get_curline(), curwin->w_cursor.col, options, count, NULL, file_lnum);\n"
	z10lit39 = "    if (buf->b_ffname == NULL)\n"
	z10lit40 = "            *argp = curbuf->b_fname;\n"
	z10lit41 = "            *argp = NULL;\n"
	z10lit42 = "    if (buf_spname(buf) != NULL)\n"
	z10lit43 = "            if (eap->argt & (EX_CTRLV | EX_XFILE))\n"
	z10lit44 = "            if (eap->argt & EX_CTRLV)\n"
	z10lit45 = "static int      readonlymode  = FALSE ;\n"
	z10lit46 = "    char_u      dirname[ PATH_MAX ];\n    buf_T       *buf;\n\n    mch_dirname(dirname,  PATH_MAX );\n     buf = curbuf;\n    shorten_buf_fname(buf, dirname, force);\n\n"
	z10lit47 = "static void shorten_fnames(int force);\n"
	z10lit48 = "static void shorten_fnames(void);\n"
	z10lit49 = "shorten_fnames(int force)\n"
	z10lit50 = "shorten_fnames(void)\n"
	z10lit51 = "    shorten_fnames(FALSE);\n"
	z10lit52 = "    shorten_fnames();\n"
)
