package harness

// zcaseList is tools/zcases.py's CASES, transcribed by a program.
//
// 102 keystroke cases that type their OWN text under 'paste'.  There is
// no file argument, no :edit and no :read: from zero phase 8 the editor
// has no way to name a file, so a corpus that opened one would stop
// working at the phase that took it away.
var zcaseList = []struct {
	name string
	args []string
	keys [][]byte
}{
	{"startup", []string{}, [][]byte{[]byte("\x1b:q!\r")}},
	{"ruler_move", []string{"+set paste"}, [][]byte{[]byte("ione two three\x1b"), []byte(":set nopaste\r"), []byte("0ww"), []byte("j"), []byte("\x1b:q!\r")}},
	{"showmode_ins", []string{"+set paste"}, [][]byte{[]byte("ix\x1b"), []byte(":set nopaste\r"), []byte("A"), []byte("\x1b:q!\r")}},
	{"term_report", []string{}, [][]byte{[]byte(":set term? t_Co?\r"), []byte("\x1b:q!\r")}},
	{"incr_hex", []string{"+set nrformats=hex", "+set paste"}, [][]byte{[]byte("i0x0f\x1b"), []byte(":set nopaste\r"), []byte("$\x01"), []byte("\x1b:q!\r")}},
	{"incr_bin", []string{"+set nrformats=bin", "+set paste"}, [][]byte{[]byte("i0b0101\x1b"), []byte(":set nopaste\r"), []byte("$\x01"), []byte("\x1b:q!\r")}},
	{"incr_oct", []string{"+set nrformats=octal", "+set paste"}, [][]byte{[]byte("i017\x1b"), []byte(":set nopaste\r"), []byte("$\x01"), []byte("\x1b:q!\r")}},
	{"incr_dec", []string{"+set nrformats=", "+set paste"}, [][]byte{[]byte("i42\x1b"), []byte(":set nopaste\r"), []byte("$\x01"), []byte("\x1b:q!\r")}},
	{"incr_alpha", []string{"+set nrformats=alpha", "+set paste"}, [][]byte{[]byte("iabc\x1b"), []byte(":set nopaste\r"), []byte("0\x01"), []byte("\x1b:q!\r")}},
	{"incr_unsigned", []string{"+set nrformats=unsigned", "+set paste"}, [][]byte{[]byte("i-7\x1b"), []byte(":set nopaste\r"), []byte("$\x01"), []byte("\x1b:q!\r")}},
	{"decr_hex", []string{"+set nrformats=hex", "+set paste"}, [][]byte{[]byte("i0x10\x1b"), []byte(":set nopaste\r"), []byte("$\x18"), []byte("\x1b:q!\r")}},
	{"decr_dec", []string{"+set nrformats=", "+set paste"}, [][]byte{[]byte("i42\x1b"), []byte(":set nopaste\r"), []byte("$\x18"), []byte("\x1b:q!\r")}},
	{"incr_count", []string{"+set nrformats=", "+set paste"}, [][]byte{[]byte("i5\x1b"), []byte(":set nopaste\r"), []byte("10\x01"), []byte("\x1b:q!\r")}},
	{"incr_midword", []string{"+set nrformats=", "+set paste"}, [][]byte{[]byte("iab12cd34\x1b"), []byte(":set nopaste\r"), []byte("0\x01"), []byte("$\x01"), []byte("\x1b:q!\r")}},
	{"autoindent", []string{"+set ai", "+set paste"}, [][]byte{[]byte("i    a\x1b"), []byte(":set nopaste\r"), []byte("A\rb\x1b"), []byte("\x1b:q!\r")}},
	{"ai_empty", []string{"+set ai", "+set paste"}, [][]byte{[]byte("i    a\x1b"), []byte(":set nopaste\r"), []byte("A\r\x1b"), []byte("A\rx\x1b"), []byte("\x1b:q!\r")}},
	{"format_gq", []string{"+set tw=20", "+set paste"}, [][]byte{[]byte("ione two three four five six seven eight nine ten eleven\x1b"), []byte(":set nopaste\r"), []byte("gqq"), []byte("\x1b:q!\r")}},
	{"format_comment", []string{"+set tw=20 fo=tcq comments=://", "+set paste"}, [][]byte{[]byte("i// aaa bbb ccc ddd eee fff ggg hhh\x1b"), []byte(":set nopaste\r"), []byte("gqq"), []byte("\x1b:q!\r")}},
	{"open_comment", []string{"+set fo=tcqr comments=://", "+set paste"}, [][]byte{[]byte("i// hello\x1b"), []byte(":set nopaste\r"), []byte("A\rx\x1b"), []byte("\x1b:q!\r")}},
	{"smartindent", []string{"+set si sw=4", "+set paste"}, [][]byte{[]byte("iif (x) {\x1b"), []byte(":set nopaste\r"), []byte("A\ry;\x1b"), []byte("\x1b:q!\r")}},
	{"shift_right", []string{"+set sw=4", "+set paste"}, [][]byte{[]byte("ia\rb\x1b"), []byte(":set nopaste\r"), []byte("ggVG>"), []byte("\x1b:q!\r")}},
	{"indent_op", []string{"+set sw=2", "+set paste"}, [][]byte{[]byte("ia\rb\rc\x1b"), []byte(":set nopaste\r"), []byte("gg3>>"), []byte("\x1b:q!\r")}},
	{"retab_gone", []string{"+set ts=8 sw=4 et", "+set paste"}, [][]byte{[]byte("i\x16\ta\x1b"), []byte(":set nopaste\r"), []byte(":retab\r"), []byte("\x1b:q!\r")}},
	{"ins_multi", []string{"+set paste"}, [][]byte{[]byte("ix\x1b"), []byte(":set nopaste\r"), []byte("Ahello world\x1b"), []byte("\x1b:q!\r")}},
	{"ins_ctrl_v", []string{"+set paste"}, [][]byte{[]byte("ix\x1b"), []byte(":set nopaste\r"), []byte("A\x16065\x1b"), []byte("\x1b:q!\r")}},
	{"ins_bs", []string{"+set paste"}, [][]byte{[]byte("iabc\x1b"), []byte(":set nopaste\r"), []byte("A\x08\x08Z\x1b"), []byte("\x1b:q!\r")}},
	{"ins_ctrl_w", []string{"+set paste"}, [][]byte{[]byte("ix\x1b"), []byte(":set nopaste\r"), []byte("Afoo bar\x17baz\x1b"), []byte("\x1b:q!\r")}},
	{"ins_tab_et", []string{"+set et sw=4 ts=8", "+set paste"}, [][]byte{[]byte("ix\x1b"), []byte(":set nopaste\r"), []byte("I\tA\x1b"), []byte("\x1b:q!\r")}},
	{"replace_mode", []string{"+set paste"}, [][]byte{[]byte("iabcdef\x1b"), []byte(":set nopaste\r"), []byte("0Rxyz\x1b"), []byte("\x1b:q!\r")}},
	{"ins_arrows", []string{"+set paste"}, [][]byte{[]byte("iabcdef\x1b"), []byte(":set nopaste\r"), []byte("0i\x1b[C\x1b[CZ\x1b"), []byte("\x1b:q!\r")}},
	{"mb_motion", []string{"+set paste"}, [][]byte{[]byte("icaf\xc3\xa9 na\xc3\xafve \xe6\x97\xa5\xe6\x9c\xac\xe8\xaa\x9e\x1b"), []byte(":set nopaste\r"), []byte("0wdw"), []byte("\x1b:q!\r")}},
	{"mb_dollar_x", []string{"+set paste"}, [][]byte{[]byte("i\xc3\xa0\xc3\xa9\xc3\xae\xc3\xb4\xc3\xbb\x1b"), []byte(":set nopaste\r"), []byte("$x"), []byte("\x1b:q!\r")}},
	{"mb_upper", []string{"+set paste"}, [][]byte{[]byte("i\xc3\xa0\xc3\xa9\xc3\xae \xc7\x86 \xc3\x9f\x1b"), []byte(":set nopaste\r"), []byte("gUU"), []byte("\x1b:q!\r")}},
	{"mb_tilde", []string{"+set paste"}, [][]byte{[]byte("ia\xc3\xa0B\xc3\x89\x1b"), []byte(":set nopaste\r"), []byte("0~~~~"), []byte("\x1b:q!\r")}},
	{"mb_incr", []string{"+set nrformats=hex", "+set paste"}, [][]byte{[]byte("i\xe6\x97\xa50x0f\xe6\x9c\xac\x1b"), []byte(":set nopaste\r"), []byte("0\x01"), []byte("\x1b:q!\r")}},
	{"mb_ga", []string{"+set paste"}, [][]byte{[]byte("i\xe6\x97\xa5\xe6\x9c\xac\x1b"), []byte(":set nopaste\r"), []byte("0ga"), []byte("\x1b:q!\r")}},
	{"subst_magic", []string{"+set paste"}, [][]byte{[]byte("ifoo123 bar456\x1b"), []byte(":set nopaste\r"), []byte(":%s/\\v(\\a+)(\\d+)/\\2-\\1/g\r"), []byte("\x1b:q!\r")}},
	{"subst_amp", []string{"+set paste"}, [][]byte{[]byte("iaaa\x1b"), []byte(":set nopaste\r"), []byte(":%s/a/[&]/g\r"), []byte("\x1b:q!\r")}},
	{"subst_case", []string{"+set paste"}, [][]byte{[]byte("ihello world\x1b"), []byte(":set nopaste\r"), []byte(":%s/\\w\\+/\\u&/g\r"), []byte("\x1b:q!\r")}},
	{"subst_nl", []string{"+set paste"}, [][]byte{[]byte("ia b\x1b"), []byte(":set nopaste\r"), []byte(":%s/ /\\r/\r"), []byte("\x1b:q!\r")}},
	{"subst_count", []string{"+set paste"}, [][]byte{[]byte("ix\rx\rx\x1b"), []byte(":set nopaste\r"), []byte(":%s/x/y/\r"), []byte(":1\r"), []byte("\x1b:q!\r")}},
	{"global_cmd", []string{"+set paste"}, [][]byte{[]byte("ia1\rb2\ra3\x1b"), []byte(":set nopaste\r"), []byte(":g/a/s/$/!/\r"), []byte("\x1b:q!\r")}},
	{"vglobal", []string{"+set paste"}, [][]byte{[]byte("ia1\rb2\ra3\x1b"), []byte(":set nopaste\r"), []byte(":v/a/d\r"), []byte("\x1b:q!\r")}},
	{"search_off", []string{"+set paste"}, [][]byte{[]byte("iaaa\rbbb\rccc\x1b"), []byte(":set nopaste\r"), []byte("gg/bbb\r"), []byte("dd"), []byte("\x1b:q!\r")}},
	{"search_wrap", []string{"+set paste"}, [][]byte{[]byte("iaaa\rbbb\x1b"), []byte(":set nopaste\r"), []byte("gg/aaa\r"), []byte("n"), []byte("\x1b:q!\r")}},
	{"dw_de_db", []string{"+set paste"}, [][]byte{[]byte("ione two three four\x1b"), []byte(":set nopaste\r"), []byte("0dwdee"), []byte("\x1b:q!\r")}},
	{"ci_quote", []string{"+set paste"}, [][]byte{[]byte("isay \"hello\" now\x1b"), []byte(":set nopaste\r"), []byte("0f\"ci\"bye\x1b"), []byte("\x1b:q!\r")}},
	{"da_paren", []string{"+set paste"}, [][]byte{[]byte("if(a, b) end\x1b"), []byte(":set nopaste\r"), []byte("0f,da("), []byte("\x1b:q!\r")}},
	{"yank_put", []string{"+set paste"}, [][]byte{[]byte("ione\rtwo\x1b"), []byte(":set nopaste\r"), []byte("ggyyGp"), []byte("\x1b:q!\r")}},
	{"visual_block", []string{"+set paste"}, [][]byte{[]byte("iabcd\refgh\rijkl\x1b"), []byte(":set nopaste\r"), []byte("gg0\x16jjlx"), []byte("\x1b:q!\r")}},
	{"join_lines", []string{"+set paste"}, [][]byte{[]byte("ia\rb\rc\x1b"), []byte(":set nopaste\r"), []byte("ggJJ"), []byte("\x1b:q!\r")}},
	{"join_gJ", []string{"+set paste"}, [][]byte{[]byte("ia\r  b\x1b"), []byte(":set nopaste\r"), []byte("gggJ"), []byte("\x1b:q!\r")}},
	{"dot_repeat", []string{"+set paste"}, [][]byte{[]byte("ia b c d\x1b"), []byte(":set nopaste\r"), []byte("0dw.."), []byte("\x1b:q!\r")}},
	{"macro_q", []string{"+set nrformats=", "+set paste"}, [][]byte{[]byte("i1\r1\r1\x1b"), []byte(":set nopaste\r"), []byte("ggqaA!\x1bjq"), []byte("2@a"), []byte("\x1b:q!\r")}},
	{"percent_match", []string{"+set paste"}, [][]byte{[]byte("if(a, b) end\x1b"), []byte(":set nopaste\r"), []byte("0f(%"), []byte("\x1b:q!\r")}},
	{"undo_redo", []string{"+set paste"}, [][]byte{[]byte("ia\rb\rc\x1b"), []byte(":set nopaste\r"), []byte("ggdddd"), []byte("u"), []byte("\x12"), []byte("u"), []byte("\x1b:q!\r")}},
	{"undo_block", []string{"+set paste"}, [][]byte{[]byte("iabc\x1b"), []byte(":set nopaste\r"), []byte("0xxx"), []byte("uu"), []byte("\x1b:q!\r")}},
	{"undo_after_ins", []string{"+set paste"}, [][]byte{[]byte("ix\x1b"), []byte(":set nopaste\r"), []byte("Aabc\x1b"), []byte("u"), []byte("\x1b:q!\r")}},
	{"undo_U", []string{"+set paste"}, [][]byte{[]byte("iabc\x1b"), []byte(":set nopaste\r"), []byte("0x"), []byte("U"), []byte("\x1b:q!\r")}},
	{"registers", []string{"+set paste"}, [][]byte{[]byte("ia\rb\x1b"), []byte(":set nopaste\r"), []byte("gg\"ryy"), []byte("G\"rp"), []byte("\x1b:q!\r")}},
	{"reg_list", []string{"+set paste"}, [][]byte{[]byte("ia\x1b"), []byte(":set nopaste\r"), []byte("yy"), []byte(":registers\r"), []byte("\x1b:q!\r")}},
	{"marks", []string{"+set paste"}, [][]byte{[]byte("ia\rb\rc\x1b"), []byte(":set nopaste\r"), []byte("ggmaG"), []byte("d'a"), []byte("\x1b:q!\r")}},
	{"mark_list", []string{"+set paste"}, [][]byte{[]byte("ia\rb\x1b"), []byte(":set nopaste\r"), []byte("ggma"), []byte(":marks\r"), []byte("\x1b:q!\r")}},
	{"move_copy", []string{"+set paste"}, [][]byte{[]byte("i1\r2\r3\x1b"), []byte(":set nopaste\r"), []byte(":2m0\r"), []byte(":1t$\r"), []byte("\x1b:q!\r")}},
	{"normal_range", []string{"+set paste"}, [][]byte{[]byte("ia\rb\rc\x1b"), []byte(":set nopaste\r"), []byte(":%normal A!\r"), []byte("\x1b:q!\r")}},
	{"sort_gone", []string{"+set paste"}, [][]byte{[]byte("ib\ra\x1b"), []byte(":set nopaste\r"), []byte(":sort u\r"), []byte("\x1b:q!\r")}},
	{"filter_gone", []string{"+set paste"}, [][]byte{[]byte("ic\ra\x1b"), []byte(":set nopaste\r"), []byte(":%!sort\r"), []byte("\x1b:q!\r")}},
	{"read_cmd_gone", []string{"+set paste"}, [][]byte{[]byte("ix\x1b"), []byte(":set nopaste\r"), []byte(":r !echo piped\r"), []byte("\x1b:q!\r")}},
	{"put_expr_gone", []string{"+set paste"}, [][]byte{[]byte("ix\x1b"), []byte(":set nopaste\r"), []byte(":put ='added'\r"), []byte("\x1b:q!\r")}},
	{"ff_gone", []string{"+set paste"}, [][]byte{[]byte("ia\x1b"), []byte(":set nopaste\r"), []byte(":set ff=dos\r"), []byte("\x1b:q!\r")}},
	{"bomb_gone", []string{"+set paste"}, [][]byte{[]byte("ia\x1b"), []byte(":set nopaste\r"), []byte(":set bomb\r"), []byte("\x1b:q!\r")}},
	{"hlsearch_opt", []string{"+set hlsearch", "+set paste"}, [][]byte{[]byte("ialpha\rbeta\rgamma\x1b"), []byte(":set nopaste\r"), []byte("gg/beta\r"), []byte("\x1b:q!\r")}},
	{"incsearch_opt", []string{"+set incsearch", "+set paste"}, [][]byte{[]byte("ialpha\rbeta\rgamma\x1b"), []byte(":set nopaste\r"), []byte("gg/gam"), []byte("\x1b:q!\r")}},
	{"match_cmd", []string{"+set paste"}, [][]byte{[]byte("ialpha\rbeta\x1b"), []byte(":set nopaste\r"), []byte(":match Search /beta/\r"), []byte("\x1b:q!\r")}},
	{"nohlsearch", []string{"+set hls", "+set paste"}, [][]byte{[]byte("ialpha\rbeta\x1b"), []byte(":set nopaste\r"), []byte("gg/beta\r"), []byte(":nohlsearch\r"), []byte("\x1b:q!\r")}},
	{"search_count", []string{"+set paste"}, [][]byte{[]byte("iaa\raa\raa\x1b"), []byte(":set nopaste\r"), []byte("gg/aa\r"), []byte("n"), []byte("\x1b:q!\r")}},
	{"nav_arrows", []string{"+set paste"}, [][]byte{[]byte("il1\rl2\rl3\x1b"), []byte(":set nopaste\r"), []byte("gg"), []byte("\x1b[B\x1b[B\x1b[C"), []byte("x"), []byte("\x1b:q!\r")}},
	{"nav_home_end", []string{"+set paste"}, [][]byte{[]byte("iabcdef\x1b"), []byte(":set nopaste\r"), []byte("0"), []byte("\x1b[F"), []byte("x"), []byte("\x1b[H"), []byte("x"), []byte("\x1b:q!\r")}},
	{"scroll_ctrl_f", []string{}, [][]byte{[]byte("iline1\rline2\rline3\rline4\rline5\rline6\rline7\rline8\rline9\rline10\rline11\rline12\rline13\rline14\rline15\rline16\rline17\rline18\rline19\rline20\rline21\rline22\rline23\rline24\rline25\rline26\rline27\rline28\rline29\rline30\rline31\rline32\rline33\rline34\rline35\rline36\rline37\rline38\rline39\rline40\x1b"), []byte("gg"), []byte("\x06"), []byte("\x1b:q!\r")}},
	{"scroll_zz", []string{}, [][]byte{[]byte("iline1\rline2\rline3\rline4\rline5\rline6\rline7\rline8\rline9\rline10\rline11\rline12\rline13\rline14\rline15\rline16\rline17\rline18\rline19\rline20\rline21\rline22\rline23\rline24\rline25\rline26\rline27\rline28\rline29\rline30\rline31\rline32\rline33\rline34\rline35\rline36\rline37\rline38\rline39\rline40\x1b"), []byte("20G"), []byte("zz"), []byte("\x1b:q!\r")}},
	{"ctrl_g", []string{"+set paste"}, [][]byte{[]byte("ia\rb\x1b"), []byte(":set nopaste\r"), []byte("\x07"), []byte("\x1b:q!\r")}},
	{"ctrl_g_count", []string{"+set paste"}, [][]byte{[]byte("ia\rb\x1b"), []byte(":set nopaste\r"), []byte("g\x07"), []byte("\x1b:q!\r")}},
	{"visual_show", []string{"+set paste"}, [][]byte{[]byte("iabcdef\x1b"), []byte(":set nopaste\r"), []byte("0vlll"), []byte("\x1b:q!\r")}},
	{"set_listing", []string{}, [][]byte{[]byte(":set nu list\r"), []byte("\x1b:q!\r")}},
	{"hit_enter", []string{}, [][]byte{[]byte(":history\r"), []byte("\x1b:q!\r")}},
	{"unknown_cmd", []string{}, [][]byte{[]byte(":nosuchcmd\r"), []byte("\x1b:q!\r")}},
	{"quit_modified", []string{"+set paste"}, [][]byte{[]byte("ix\x1b"), []byte(":set nopaste\r"), []byte(":q\r"), []byte("\x1b:q!\r")}},
	{"zz_key", []string{"+set paste"}, [][]byte{[]byte("ix\x1b"), []byte(":set nopaste\r"), []byte("ZZ"), []byte("\x1b:q!\r")}},
	{"map_tab_percent", []string{"+set paste"}, [][]byte{[]byte("if(a, b) end\x1b"), []byte(":set nopaste\r"), []byte("0f("), []byte("\t"), []byte("\x1b:q!\r")}},
	{"map_e_acute_undo", []string{"+set paste"}, [][]byte{[]byte("iabc\x1b"), []byte(":set nopaste\r"), []byte("0x"), []byte("\xc3\xa9"), []byte("\x1b:q!\r")}},
	{"map_in_paste", []string{"+set paste"}, [][]byte{[]byte("ix\xc2\xa7y\x1b"), []byte(":set nopaste\r"), []byte("\x1b:q!\r")}},
	{"map_list", []string{}, [][]byte{[]byte(":map\r"), []byte("\x1b:q!\r")}},
	{"ctrl_c_clean", []string{}, [][]byte{[]byte("\x03"), []byte("\x1b:q!\r")}},
	{"ctrl_c_changed", []string{"+set paste"}, [][]byte{[]byte("ix\x1b"), []byte(":set nopaste\r"), []byte("\x03"), []byte("\x1b:q!\r")}},
	{"key_Q", []string{"+set paste"}, [][]byte{[]byte("ialpha\rbeta\x1b"), []byte(":set nopaste\r"), []byte("Q"), []byte("\x1b:q!\r")}},
	{"key_gQ", []string{"+set paste"}, [][]byte{[]byte("ialpha\rbeta\x1b"), []byte(":set nopaste\r"), []byte("gQ"), []byte("\x1b:q!\r")}},
	{"cmd_write", []string{"+set paste"}, [][]byte{[]byte("ix\x1b"), []byte(":set nopaste\r"), []byte(":write\r"), []byte("\x1b:q!\r")}},
	{"cmd_read", []string{"+set paste"}, [][]byte{[]byte("ix\x1b"), []byte(":set nopaste\r"), []byte(":read\r"), []byte("\x1b:q!\r")}},
	{"cmd_edit", []string{"+set paste"}, [][]byte{[]byte("ix\x1b"), []byte(":set nopaste\r"), []byte(":edit\r"), []byte("\x1b:q!\r")}},
	{"cmd_file", []string{"+set paste"}, [][]byte{[]byte("ix\x1b"), []byte(":set nopaste\r"), []byte(":file\r"), []byte("\x1b:q!\r")}},
	{"key_gf", []string{"+set paste"}, [][]byte{[]byte("inosuchfile\x1b"), []byte(":set nopaste\r"), []byte("0gf"), []byte("\x1b:q!\r")}},
	{"reg_percent", []string{"+set paste"}, [][]byte{[]byte("ix\x1b"), []byte(":set nopaste\r"), []byte("A \x12%\x1b"), []byte("\x1b:q!\r")}},
}
