package harness

// zmemCases is tools/zmemline.py's CASES, transcribed by a program.
//
// Sixteen cases of 200 to 25,000 lines, built IN THE EDITOR: there is no
// file argument, no :edit and no :read.  Their depth is MEASURED and not
// intended -- a data block splits in 16 of 16 and the root in 4, against
// 0 of 102 for all seven markers in the screen corpus -- which is why
// this part exists at all: until it did, nothing in the pipeline could
// tell a working memline from a broken one.
var zmemCases = []struct {
	name string
	args []string
	keys [][]byte
}{
	{"mem_two_blocks", []string{"+set paste"}, [][]byte{[]byte("i000001 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\x1b"), []byte(":set nopaste\r"), []byte(":set nrformats=\r"), []byte("qqyyp\x01q"), []byte("198@q"), []byte(":100\r"), []byte("dd"), []byte("Oinserted\x1b"), []byte(":set number\r"), []byte(":%s/^/&/n\r"), []byte(":%s/\\d/&/n\r"), []byte(":1\r"), []byte("\x07"), []byte(":100\r"), []byte("\x07"), []byte(":150\r"), []byte("\x07"), []byte("gg"), []byte("\x07"), []byte("G"), []byte("\x07"), []byte("\x1b:q!\r")}},
	{"mem_many_blocks", []string{"+set paste"}, [][]byte{[]byte("i000001 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\x1b"), []byte(":set nopaste\r"), []byte(":set nrformats=\r"), []byte("qqyyp\x01q"), []byte("3998@q"), []byte(":2000\r"), []byte("dd"), []byte(":set number\r"), []byte(":%s/^/&/n\r"), []byte(":%s/\\d/&/n\r"), []byte(":1\r"), []byte("\x07"), []byte(":1000\r"), []byte("\x07"), []byte(":2000\r"), []byte("\x07"), []byte(":3000\r"), []byte("\x07"), []byte("gg"), []byte("\x07"), []byte("G"), []byte("\x07"), []byte("\x1b:q!\r")}},
	{"mem_root_split", []string{"+set paste"}, [][]byte{[]byte("i000001 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\x1b"), []byte(":set nopaste\r"), []byte(":set nrformats=\r"), []byte("qqyyp\x01q"), []byte("11998@q"), []byte(":set number\r"), []byte(":%s/^/&/n\r"), []byte(":%s/\\d/&/n\r"), []byte(":1\r"), []byte("\x07"), []byte(":6000\r"), []byte("\x07"), []byte(":11999\r"), []byte("\x07"), []byte("gg"), []byte("\x07"), []byte("G"), []byte("\x07"), []byte("\x1b:q!\r")}},
	{"mem_deep_jumps", []string{"+set paste"}, [][]byte{[]byte("i000001 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\x1b"), []byte(":set nopaste\r"), []byte(":set nrformats=\r"), []byte("qqyyp\x01q"), []byte("24998@q"), []byte(":24000\r"), []byte(":1\r"), []byte(":12345\r"), []byte(":300\r"), []byte(":19999\r"), []byte(":7\r"), []byte(":22222\r"), []byte(":set number\r"), []byte(":%s/^/&/n\r"), []byte(":%s/\\d/&/n\r"), []byte(":1\r"), []byte("\x07"), []byte(":12500\r"), []byte("\x07"), []byte(":24999\r"), []byte("\x07"), []byte("gg"), []byte("\x07"), []byte("G"), []byte("\x07"), []byte("\x1b:q!\r")}},
	{"mem_mid_insert", []string{"+set paste"}, [][]byte{[]byte("i000001 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\x1b"), []byte(":set nopaste\r"), []byte(":set nrformats=\r"), []byte("qqyyp\x01q"), []byte("3998@q"), []byte(":2000\r"), []byte("400oinserted line here\x1b"), []byte(":set number\r"), []byte(":%s/^/&/n\r"), []byte(":%s/\\d/&/n\r"), []byte(":1900\r"), []byte("\x07"), []byte(":2100\r"), []byte("\x07"), []byte(":2500\r"), []byte("\x07"), []byte("gg"), []byte("\x07"), []byte("G"), []byte("\x07"), []byte("\x1b:q!\r")}},
	{"mem_mid_delete", []string{"+set paste"}, [][]byte{[]byte("i000001 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\x1b"), []byte(":set nopaste\r"), []byte(":set nrformats=\r"), []byte("qqyyp\x01q"), []byte("3998@q"), []byte(":1500\r"), []byte("1000dd"), []byte(":set number\r"), []byte(":%s/^/&/n\r"), []byte(":%s/\\d/&/n\r"), []byte(":1\r"), []byte("\x07"), []byte(":1400\r"), []byte("\x07"), []byte(":1600\r"), []byte("\x07"), []byte("gg"), []byte("\x07"), []byte("G"), []byte("\x07"), []byte("\x1b:q!\r")}},
	{"mem_mid_replace", []string{"+set paste"}, [][]byte{[]byte("i000001 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\x1b"), []byte(":set nopaste\r"), []byte(":set nrformats=\r"), []byte("qqyyp\x01q"), []byte("3998@q"), []byte(":1000,2000s/a/B/g\r"), []byte(":set number\r"), []byte(":%s/^/&/n\r"), []byte(":%s/\\d/&/n\r"), []byte(":999\r"), []byte("\x07"), []byte(":1500\r"), []byte("\x07"), []byte(":2001\r"), []byte("\x07"), []byte("gg"), []byte("\x07"), []byte("G"), []byte("\x07"), []byte("\x1b:q!\r")}},
	{"mem_split_root_mid", []string{"+set paste"}, [][]byte{[]byte("i000001 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\x1b"), []byte(":set nopaste\r"), []byte(":set nrformats=\r"), []byte("qqyyp\x01q"), []byte("11998@q"), []byte(":6000\r"), []byte("200oxxxx\x1b"), []byte("500dd"), []byte(":set number\r"), []byte(":%s/^/&/n\r"), []byte(":%s/\\d/&/n\r"), []byte(":5900\r"), []byte("\x07"), []byte(":6100\r"), []byte("\x07"), []byte(":11000\r"), []byte("\x07"), []byte("gg"), []byte("\x07"), []byte("G"), []byte("\x07"), []byte("\x1b:q!\r")}},
	{"mem_long_line", []string{"+set paste"}, [][]byte{[]byte("i000001 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\x1b"), []byte(":set nopaste\r"), []byte(":set nrformats=\r"), []byte("qqyyp\x01q"), []byte("198@q"), []byte(":100\r"), []byte("4200ix\x1b"), []byte(":set number\r"), []byte(":%s/^/&/n\r"), []byte(":%s/\\d/&/n\r"), []byte(":99\r"), []byte("\x07"), []byte(":100\r"), []byte("\x07"), []byte(":101\r"), []byte("\x07"), []byte("gg"), []byte("\x07"), []byte("G"), []byte("\x07"), []byte("\x1b:q!\r")}},
	{"mem_mixed_len", []string{"+set paste"}, [][]byte{[]byte("i000001 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\x1b"), []byte(":set nopaste\r"), []byte(":set nrformats=\r"), []byte("qqyyp\x01q"), []byte("998@q"), []byte(":200\r"), []byte("2000iy\x1b"), []byte(":400\r"), []byte("6000iz\x1b"), []byte(":600\r"), []byte("80iw\x1b"), []byte(":set number\r"), []byte(":%s/^/&/n\r"), []byte(":%s/\\d/&/n\r"), []byte(":200\r"), []byte("\x07"), []byte(":400\r"), []byte("\x07"), []byte(":600\r"), []byte("\x07"), []byte("gg"), []byte("\x07"), []byte("G"), []byte("\x07"), []byte("\x1b:q!\r")}},
	{"mem_global_del", []string{"+set paste"}, [][]byte{[]byte("i000001 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\x1b"), []byte(":set nopaste\r"), []byte(":set nrformats=\r"), []byte("qqyyp\x01q"), []byte("3998@q"), []byte(":g/3 a/d\r"), []byte(":set number\r"), []byte(":%s/^/&/n\r"), []byte(":%s/\\d/&/n\r"), []byte(":1\r"), []byte("\x07"), []byte(":1000\r"), []byte("\x07"), []byte(":3000\r"), []byte("\x07"), []byte("gg"), []byte("\x07"), []byte("G"), []byte("\x07"), []byte("\x1b:q!\r")}},
	{"mem_global_sub", []string{"+set paste"}, [][]byte{[]byte("i000001 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\x1b"), []byte(":set nopaste\r"), []byte(":set nrformats=\r"), []byte("qqyyp\x01q"), []byte("3998@q"), []byte(":g/7 a/s/a/Q/\r"), []byte(":set number\r"), []byte(":%s/^/&/n\r"), []byte(":%s/\\d/&/n\r"), []byte(":1\r"), []byte("\x07"), []byte(":2000\r"), []byte("\x07"), []byte(":3500\r"), []byte("\x07"), []byte("gg"), []byte("\x07"), []byte("G"), []byte("\x07"), []byte("\x1b:q!\r")}},
	{"mem_sort", []string{"+set paste"}, [][]byte{[]byte("i000001 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\x1b"), []byte(":set nopaste\r"), []byte(":set nrformats=\r"), []byte("qqyyp\x01q"), []byte("2998@q"), []byte(":sort!\r"), []byte(":sort\r"), []byte(":set number\r"), []byte(":%s/^/&/n\r"), []byte(":%s/\\d/&/n\r"), []byte(":1\r"), []byte("\x07"), []byte(":1500\r"), []byte("\x07"), []byte(":2999\r"), []byte("\x07"), []byte("gg"), []byte("\x07"), []byte("G"), []byte("\x07"), []byte("\x1b:q!\r")}},
	{"mem_join_split", []string{"+set paste"}, [][]byte{[]byte("i000001 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\x1b"), []byte(":set nopaste\r"), []byte(":set nrformats=\r"), []byte("qqyyp\x01q"), []byte("1998@q"), []byte(":1000,1400j\r"), []byte(":%s/ a/\\r/\r"), []byte(":set number\r"), []byte(":%s/^/&/n\r"), []byte(":%s/\\d/&/n\r"), []byte(":1\r"), []byte("\x07"), []byte(":990\r"), []byte("\x07"), []byte(":1100\r"), []byte("\x07"), []byte("gg"), []byte("\x07"), []byte("G"), []byte("\x07"), []byte("\x1b:q!\r")}},
	{"mem_undo_storm", []string{"+set paste"}, [][]byte{[]byte("i000001 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\x1b"), []byte(":set nopaste\r"), []byte(":set nrformats=\r"), []byte("qqyyp\x01q"), []byte("3998@q"), []byte(":2000\r"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("dd"), []byte("30u"), []byte("30\x12"), []byte("30u"), []byte(":set number\r"), []byte(":%s/^/&/n\r"), []byte(":%s/\\d/&/n\r"), []byte(":1\r"), []byte("\x07"), []byte(":1990\r"), []byte("\x07"), []byte(":2010\r"), []byte("\x07"), []byte("gg"), []byte("\x07"), []byte("G"), []byte("\x07"), []byte("\x1b:q!\r")}},
	{"mem_undo_big", []string{"+set paste"}, [][]byte{[]byte("i000001 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\x1b"), []byte(":set nopaste\r"), []byte(":set nrformats=\r"), []byte("qqyyp\x01q"), []byte("11998@q"), []byte(":6000\r"), []byte("2000dd"), []byte("u"), []byte("\x12"), []byte("u"), []byte(":set number\r"), []byte(":%s/^/&/n\r"), []byte(":%s/\\d/&/n\r"), []byte(":1\r"), []byte("\x07"), []byte(":6000\r"), []byte("\x07"), []byte(":11999\r"), []byte("\x07"), []byte("gg"), []byte("\x07"), []byte("G"), []byte("\x07"), []byte("\x1b:q!\r")}},
}
